name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Remove old project
            rm -rf ~/react-app
            mkdir ~/react-app
            cd ~/react-app

            # Clone latest code
            git clone https://github.com/sahilMahadik2002/aws-assignment.git .

            # Ensure vite.config.js has base: './'
            sed -i "s|base: .*|base: './',|" vite.config.js || echo "Check vite.config.js manually if this fails."

            # Install dependencies & build
            npm install
            npm run build

            # Kill old serve processes if any
            pkill -f "serve" || true

            # Serve the app bound to 0.0.0.0:5712
            nohup npx serve -s dist -l http://0.0.0.0:5712 > serve.log 2>&1 &
          EOF
