name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Debug SSH Environment
        run: |
          echo "USER: ${{ secrets.EC2_USER }}"
          echo "HOST: ${{ secrets.EC2_HOST }}"

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/react-app
            if [ ! -d ".git" ]; then
              git clone https://github.com/sahilMahadik2002/aws-assignment.git .
            else
              git pull origin main
            fi
            npm install
            npm run build
            npx serve -s build -l 3000 &
          EOF
